### ISSUE TITLE
The code is compilable with Eclipse, but not with javac

### ISSUE THREAD

**Issue by slavat** [nicolasgramlich/AndEngineMultiplayerExtension#1]
The code uses some Java features which are compilable with Eclipse built-in compiler but not compilable with Oracle's javac compiler. Therefore the code is also not compilable with Ant, IntelliJ IDEA, Netbeans, etc.

More details here: https://code.google.com/p/andenginemultiplayerextension/issues/detail?id=2

**Comment by nicolasgramlich** [comment]
Thanks for posting this here, I'll address it as soon as I have the time =(

Sidenote: I shouldn't rely on Eclipse that much =(

**Comment by guillaumepoirire** [comment]
I can't compile it using the NetBeans android plugin, the output is on this gist https://gist.github.com/1865508.

Also the issue seems to come from two files :
org.andengine.extension.multiplayer.protocol.client.IServerMessageHandler
org.andengine.extension.multiplayer.protocol.server.SocketServerDiscoveryServer

**Comment by sephyroth69** [comment]
Same error here with intellij 11.0.2, though a quick patch I found is to set intellij to use Eclipse compiler in the settings/compiler menu (there are several options) and everything seems to compile properly.

**Comment by ghost** [comment]
Disappointing that this is still an issue.. as a non-Eclipse user I've found AndEngine to be very unapproachable

**Comment by nicolasgramlich** [comment]
Fixed.
